### PR TITLE
Simple-app

### PR DESCRIPTION
**Pull request by sirpy**
Add a simple app mode when visiting ?simpleapp=true
It will not show any wallet connect option and will try to auto connect to the injected wallet.
in swap mode it will automatically set the target swap to cUSD

TODO:
- [x] after claim show a button to "swap to cusd"
- [ ] design/clean "swap to cusd OR"
- [ ] make it clearer that you should click on "use your G$"
- [ ] fix centering of swap page
image
image

### CODE REVIEW

**Comment by sirpy** [comment]
@patpedrosa 
See the screen in the description.
Needs to make it look good. plus i believe the blue box is not clear enough that it's a call to action to click on it

**Comment by L03TJ3** [comment]
@sirpy The space at the top is because we center the uniswap-widget.
if we don't do this there will be a huge gap at the bottom (for larger-height screens)
this because the bottom-bar is fixed to the bottom of screen

Ofcourse this we could change but then we have to refactor the structure since the bottom-bar on mobile is hacked to the bottom (where it actually is inside the top-bar div)

**Comment by sirpy** [comment]
@L03TJ3 ok so we should fix it, either try to find a universal way to center it with/without bottom bar or customize center for the state (isSimpleApp) when no bottom bar

**Comment by sirpy** [comment]
@L03TJ3 @patpedrosa i've opened the issue #455 for this

**Pull request merged**
