### PR TITLE
fix: user should select correct network on metamask

### PR DESCRIPTION
**Pull request by imanshu03**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

About # (link your issue here)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

### CODE REVIEW

**Comment by imanshu03** [comment]
@sirpy Please review this ticket. I have reverted the network select changes and used window ethereum only if user is on metamask

**Comment by sirpy** [comment]
@imanshu03 i need you to first REVERT the previous PR
and then add your changes so I can understand what happened, that previous PR had lots of changes
describe in the new full PR what where the things you changed

**Comment by imanshu03** [comment]
@sirpy previous PR has been already merged into master branch, I'll create a PR to revert previous changes. Please merge that it in master and after that I'll create a new PR with new changes

**Comment by imanshu03** [comment]
@sirpy I have reverted the previous PR changes. Please review and merge this so that I can again give the PR with new changes.

**Review by adaptivecodeio — APPROVED** [review]

**Comment by sirpy** [comment]
@imanshu03 when i look at https://github.com/GoodDollar/GoodProtocolUI/pull/66/files
there are many more changes than you restored here.
maybe its better that you start explaining what are all the changes you did, why are they required, are they still required, what else needs to be fixed

**Comment by sirpy** [comment]
@imanshu03 is this change is the reason why its not working on browsers without metamask?
@adaptivecodeio we need to fix that BUG asap... hotfix it with the minimum requirements

**Comment by imanshu03** [comment]
@sirpy I have reverted the changes done for ticket 37 as you said I hardcoded it for metamask. Now the WalletModal and NetworkModal does not contain any change for handling correct select network. Once you will approve this and merge it in master after that I'll provide you with another PR which will contain the changes to handle correct selection of network when user is on metamask.

**Pull request merged**
